// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbJPK5L2WnKwhCvjr8ddTfIP70UIMvS04',
    appId: '1:1023055512375:android:3fbdf9bff6b4c538fb50b2',
    messagingSenderId: '1023055512375',
    projectId: 'todo-list-daliy',
    storageBucket: 'todo-list-daliy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAetSTvKBw-GwcJ_BEf11bBhDDaqUvpVfw',
    appId: '1:1023055512375:ios:0f1617be0ddc2039fb50b2',
    messagingSenderId: '1023055512375',
    projectId: 'todo-list-daliy',
    storageBucket: 'todo-list-daliy.firebasestorage.app',
    iosBundleId: 'com.list.task.todo.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsCS28lr5g47JrkKvQuHkHDP5woHXOFfQ',
    appId: '1:1023055512375:web:58c556c32a20fe5bfb50b2',
    messagingSenderId: '1023055512375',
    projectId: 'todo-list-daliy',
    authDomain: 'todo-list-daliy.firebaseapp.com',
    storageBucket: 'todo-list-daliy.firebasestorage.app',
    measurementId: 'G-1DLE77RCNR',
  );
}
